project:
  type: website

website:
  title: "testproject"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: autocorrectborders.qmd
        text: Autocorrectborders

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
